elastacloud/parquet-dotnet

src/Parquet.Test/Reader/ParquetCsvComparison.cs, src/Parquet.Test/Reader/TestDataTest.cs, src/Parquet/File/Values/PlainValuesReader.cs, src/Parquet/ParquetColumn.cs, src/Parquet/ParquetDataSet.cs
Fixes #
Added check for new logical JSON type to treat like a string in the same way as UTF8
- [ *] unit/integration tests
- [ *] documentation
=> 16 json logical types

src/parq/Display/ColumnDetails.cs, src/parq/Display/ConsoleSheet.cs, src/parq/Display/DisplayController.cs, src/parq/Display/ViewModel.cs, src/parq/Display/ViewPort.cs, src/parq/Display/Views/ConsoleView.cs, src/parq/Display/Views/Input.cs, src/parq/Program.cs
Issue #69 
Allows for horizontal scrolling through data sets. See issue #70 for next steps in making parq more interactive at the cmdline.
=> Parq wide - Implement horizontal 

src/parq/Display/DisplayController.cs, src/parq/Display/Models/ColumnDetails.cs, src/parq/Display/Models/ConsoleFold.cs, src/parq/Display/Models/ConsoleSheet.cs, src/parq/Display/Models/ViewModel.cs, src/parq/Display/Views/ConsoleView.cs, src/parq/Display/Views/Input.cs
Issue #70 
Allows the scrolling of data upsy downsy.
=> #70 row-wise folding

src/Parquet.Test/EndToEndTypeTest.cs, src/Parquet.Test/ParquetWriterTest.cs, src/Parquet/File/Values/PlainValuesWriter.cs
Issue #95 
fails any time when character in utf-8 is not taking 1 byte
=> fixing bug in UTF-8 strings writer

README.md, src/Parquet.Test/CompressionTest.cs, src/Parquet.Test/DataSetTest.cs, src/Parquet.Test/EndToEndTypeTest.cs, src/Parquet.Test/File/Values/PlainValuesReaderWriterTest.cs, src/Parquet.Test/ParquetWriterTest.cs, src/Parquet.Test/Reader/ParquetCsvComparison.cs, src/Parquet/Data/ColumnStats.cs, src/Parquet/Data/DataSet.cs, src/Parquet/Data/DataSetStats.cs, src/Parquet/Data/Schema.cs, src/Parquet/Data/SchemaElement.cs, src/Parquet/File/MetaBuilder.cs, src/Parquet/File/Values/ByteGarbage.cs, src/Parquet/File/Values/RunLengthBitPackingHybridValuesReader.cs, src/Parquet/File/Values/RunLengthBitPackingHybridValuesWriter.cs, src/Parquet/ParquetReader.cs, src/Parquet/ParquetWriter.cs
Issue #79, #34 
This implementation allow to write null values. Writer will detect if a column has null value and change schema appropriately + write definition level encoding.
Boolean flag removed from SchemaElement which used to indicate whether column is nullable, as this is automatically detected.
=> 79 nullable cols

src/Parquet.Test/EndToEndTypeTest.cs, src/Parquet/File/TypeFactory.cs, src/Parquet/File/Values/PlainValuesWriter.cs
Issue #103 
floats and doubles couldn't be written
=> add support for floats and doubles

src/parq/Program.cs, src/parq/parq.csproj
Issue #109 - Removes LogMagic and uses Console primitives.
=> 109 parameterless help

doc/dataset.md, doc/features.md, src/Parquet.Test/EndToEndTypeTest.cs, src/Parquet.Test/ParquetReaderOnTestFilesTest.cs, src/Parquet.Test/ParquetWriterTest.cs, src/Parquet/Data/DateTimeFormat.cs, src/Parquet/Data/SchemaElement.cs, src/Parquet/File/Values/PlainValuesReader.cs, src/Parquet/File/Values/PlainValuesWriter.cs, src/Parquet/ParquetUtils.cs, src/Parquet/Thrift/ConvertedType.cs, src/Parquet/Thrift/Type.cs, src/parq/Program.cs, src/parq/parq.csproj
no issue
This hides internal Thrift types back and I believe allows to specify date format more expressively when required. Documentation updated to reflect this too.
This change introduces tests which are failing, however this is only due to the fact there is a problem in reading or writing dates which differs in one day.
=> dates review

src/Parquet.Test/CompressionTest.cs, src/Parquet/File/Data/SnappyDataWriter.cs
Issue #115 
fix bug with snappy compression
=> fix snappy bug

src/Parquet/Data/SchemaElement.cs, src/Parquet/File/Values/PlainValuesReader.cs, src/Parquet/File/Values/PlainValuesWriter.cs
Issue #75 
Used parquetoptions properties to toggle between dates and bigintegers
=> 75 int96 read as raw type

src/Parquet.sln, src/parq/AppSettings.cs, src/parq/Display/DisplayController.cs, src/parq/Display/Views/FullConsoleView.cs, src/parq/Display/Views/InteractiveConsoleView.cs
Issue #121 
Shows more details per column.
=> Parq fuller

scripts/choco/package.ps1, scripts/choco/parq/parq.nuspec, scripts/choco/parq/tools/ReadMe.md, scripts/choco/parq/tools/chocolateyinstall.ps1, scripts/choco/parq/tools/chocolateyuninstall.ps1, src/parq/AppSettings.cs, src/parq/Program.cs, src/parq/parq.csproj
=> #72 Deploy with Chocolatey

src/Parquet.Test/EndToEndTypeTest.cs, src/Parquet.Test/ParquetWriterTest.cs, src/Parquet/File/Values/PlainValuesReader.cs, src/Parquet/File/Values/PlainValuesWriter.cs, src/Parquet/File/Values/Primitives/NanoTime.cs, src/Parquet/Parquet.csproj, src/Parquet/ParquetWriter.cs
Issue #145 
I think I fixed the impala dates issues. I've found more precise conversion code, even though I don't completely understand how conversion adjustments work the tests seem to pass again. Tested on Spark that it reads it properly too.
=> fixing impala dates

src/Parquet.Test/ParquetReaderTest.cs, src/Parquet/Data/DataSet.cs, src/Parquet/Data/DataSetMetadata.cs, src/Parquet/File/MetaBuilder.cs, src/Parquet/ParquetReader.cs
Issue #136 
desctiption goes here
expose created_by metadata on dataset
=> expose created_by metadata on dataset

src/parq/Display/DisplayController.cs, src/parq/Display/Models/ConsoleFold.cs, src/parq/Display/Views/InteractiveConsoleView.cs, src/parq/Program.cs
Issue #143 
Interactive mode now reads from the source file by offset and count.
=> #143 Implement Paging in Parq Interactive

doc/parq.md, scripts/choco/parq/parq.nuspec, src/parq/AppSettings.cs, src/parq/Program.cs, src/parq/parq.csproj
Issue #144
Head and Tail features
=> #144 Implement Head and Tail Parq features

appveyor.yml, src/Parquet.sln
Issue #152 
add .yml (appveyor build definition) to local branch, to override build settings in separate branches.
=> add yml definition

src/Parquet.Test/DataSetGenerator.cs, src/Parquet.Test/File/Values/PlainDictionaryValuesReaderWriterTest.cs, src/Parquet.Test/File/Values/PlainValuesReaderWriterTest.cs, src/Parquet.Test/ParquetWriterTest.cs, src/Parquet/File/MetaBuilder.cs, src/Parquet/File/TypeFactory.cs, src/Parquet/File/Values/IValuesWriter.cs, src/Parquet/File/Values/PlainDictionaryValuesWriter.cs, src/Parquet/File/Values/PlainValuesWriter.cs, src/Parquet/File/Values/RunLengthBitPackingHybridValuesWriter.cs, src/Parquet/ParquetOptions.cs, src/Parquet/ParquetWriter.cs
Issue #141 
first implementation of dictionary encoding, only enabled for strings
=> dictionary encoding in writer

README.md, appveyor.yml, doc/features.md, src/Parquet/Parquet.csproj
=> change master version to 1.1 alpha

src/Parquet/ReaderOptions.cs
Issue #148 
theres nothing else to add, internally long is already used
=> really simple fix

appveyor.ps1
Issue #170 
Only keep latest 3 alphas on nuget.
=> script to drop alphas

src/Parquet.Test/Formats/CsvFormatTest.cs, src/Parquet/File/MetaBuilder.cs, src/Parquet/Formats/CsvFormat.cs
=> set totalrowcount and createdby IN csv

appveyor.yml, src/Parquet/File/PColumn.cs, src/Parquet/Parquet.csproj
=> release v1.1

src/Parquet.Test/EndToEndTypeTest.cs, src/Parquet/File/TypePrimitive.cs, src/Parquet/File/Values/PlainValuesReader.cs, src/Parquet/File/Values/PlainValuesWriter.cs, src/Parquet/Thrift/Type.cs
Issue #211 
Minor updates to align annotated INT_8 and UINT_8 to byte and sbyte respectively
=> added sbyte and byte as INT_8 and UINT_8 annotated types

README.md
Small issue with wrong link for contributing guidelines
Changed link in readme
=> Fix for CONTRIBUTING.md link in README

doc/parquet-getting-started.md
Fixed links in getting started to external documentation in getting started
=> Fixed links in getting started

src/Parquet.Test/EndToEndTypeTest.cs, src/Parquet/File/TypePrimitive.cs, src/Parquet/File/Values/PlainValuesReader.cs, src/Parquet/File/Values/PlainValuesWriter.cs
Issue #235 
added short and ushort types
=> added short and ushort types (#235)

src/Parquet/File/Values/Primitives/BigDecimal.cs
Issue #243 
Set decimal size according to Precision (based on Impala sources)
=> #243 fix decimal size for Impala

src/Parquet.Test/EndToEndTypeTest.cs, src/Parquet/Data/Schema/DateTimeSchemaElement.cs, src/Parquet/Data/Schema/DecimalSchemaElement.cs, src/Parquet/Data/Schema/SchemaElement.cs, src/Parquet/File/FileMetadataBuilder.cs
=> Fix Type_length for nulable decimal Issue #241

src/Parquet/Data/Concrete/BooleanDataTypeHandler.cs
Issue #305 - Bug in BooleanDataTypeHandler
The handler was increasing the 'n' variable only on true values.
=> Issue 305 - bug fix in BooleanDataTypeHandler

appveyor.yml, build.ini, src/Parquet.Test/CompressionTest.cs, src/Parquet.Test/TestBase.cs, src/Parquet/File/DataColumnWriter.cs, src/Parquet/File/DataStreamFactory.cs, src/Parquet/File/Streams/GapStream.cs, src/Parquet/File/Streams/SnappyInMemoryStream.cs, src/Parquet/File/ThriftFooter.cs, src/Parquet/Parquet.csproj
=> Compression bug in v3 compression streams

src/Parquet.Test/ParquetWriterTest.cs, src/Parquet/Data/DataColumn.cs
Issue #321
desctiption goes here
- [x ] I have included unit tests validating this fix.
=> Fix #321 cannot write nullable column without null values

build.ini, src/Parquet.CLI/Commands/SchemaCommand.cs, src/Parquet.CLI/Help.Designer.cs, src/Parquet.CLI/Help.resx, src/Parquet.CLI/Models/Input.cs, src/Parquet.CLI/Models/ViewSettings.cs, src/Parquet.CLI/Program.cs, src/Parquet.CLI/Telemetry.cs, src/Parquet.CLI/Views/InteractiveConsoleView.cs
Issue #344 
Help needs command.description or it throws.
=> hotfix; errors in parq when seeking help

src/Parquet.Test/EndToEndTypeTest.cs, src/Parquet.Test/ParquetReaderTest.cs, src/Parquet/Data/Concrete/ByteArrayDataTypeHandler.cs
…ray columns.
Issue #360 
Add support for reading ByteArray DataType.
Add some tests for ByteArray columns.
=> Add support for reading ByteArray DataType.

src/Parquet.CLI/Views/InteractiveConsoleView.cs
=> when we truncate, avoid out by one error

src/Parquet/File/Values/RunLengthBitPackingHybridValuesReader.cs
Issue #382 (potentially)
add extra check for array boundaries in RLE
=> add extra check for array boundaries in RLE

src/Parquet/Serialization/Values/ClrBridge.cs
…entDictionary and use the thread-safe API
Issue #432 
Make ClrBridge thread safe by changing _collectorKeyToTag and _assignerKeyToTag to ConcurrentDictionary and use its thread-safe APIs
Unit tests were not added since the existing unit tests already covers the scenario and ConcurrentDictionary thread safety is tested at .NET level.
=> Make ClrBridge thread safe
